### ISSUE TITLE
gebruik com_ajax

### ISSUE THREAD

**Issue by hans2103** [perfectwebteam/plg_system_rsfppostcodeapi#2]
Het zou mooi zijn als we het Joomla core component com_ajax hanteren in plaats van het php bestand in media

**Comment by sanderpotjer** [comment]
@nemphias doel is dat het php bestand voor AJAX call niet meer in media folder zit, graag in plugin zelf verwerken als dat lukt :)

**Comment by sanderpotjer** [comment]
@hans2103 is dus nu beschikbaar :-)
