### ISSUE TITLE
Andere API maken

### ISSUE THREAD

**Issue by Martijn-Boomsma** [perfectwebteam/plg_system_rsfppostcodeapi#4]
We willen andere API gaan gebruiken voor deze vanwege kosten en slechte service. Er is een onderzoekje voor beste alternatief nodig. Bijvoorbeeld:
- http://geodata.nationaalgeoregister.nl/locatieserver/free\
- https://data.overheid.nl/datasets
- https://overheid.io/documentatie/bag
- https://github.com/api-postcode

**Comment by pwtStefanPeters** [comment]
NVML: https://github.com/perfectwebteam/nvml.nl/commit/defef947d2949c49ede2195d2d498acc7a69136b

PR: https://github.com/perfectwebteam/nvml.nl/pull/432

**Comment by pwtStefanPeters** [comment]
To do's:

- [x] Readme updaten
- [x] Plugin updaten met library

**Comment by pwtStefanPeters** [comment]
Er is voor deze API gekozen die 1000 calls per dag gratis heeft:
https://www.api-postcode.nl/login

email: info@perfectwebteam.nl
pass: `\m}?a+n4mGVg(jLU-Kyu`

**Comment by Martijn-Boomsma** [comment]
@pwtStefanPeters We moeten deze bij NVML nog testen en uitrollen https://test.nvml.nl.

**Comment by pwtStefanPeters** [comment]
@sanderpotjer Getest in test omgeving. PR: https://github.com/perfectwebteam/nvml.nl/pull/432

**Comment by sanderpotjer** [comment]
@pwtStefanPeters ik heb in `public_html/libraries/Postcode` composer install uitgevoerd, maar werkt bij mij dan lokaal nog niet? Mis ik dan een stap?

**Comment by pwtStefanPeters** [comment]
@sanderpotjer Wat voor error krijg je? Werken we met dezelfde database? API is in back-end wel aangepast

**Comment by sanderpotjer** [comment]
@pwtStefanPeters top!

@Martijn-Boomsma uitgerold op nvml live.
